title: Brain Imaging Data Structure
description: A simple and intuitive way to organize and describe your neuroimaging and behavioral data.
theme: jekyll-theme-cayman

# the base hostname & protocol for your site, e.g. http://example.com
url: ""

# the subpath where the site content is hosted, including images and style sheets
# this should be "bids-website" if you host it under your own github account
baseurl: "/bids-website"

show_menu: true
show_footer: false
google_analytics: false
show_menu: true

excerpt_separator: <!--more-->

collections:
  pages:
    output: true
    permalink: /:path

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      toc: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      toc: false

include:
  - _pages
  - _posts

exclude:
  - script
  - docs
  - old_website
  - README.md
  - Gemfile*
  - jekyll-theme-cayman.gemspec
