title: Brain Imaging Data Structure
description: A simple and intuitive way to organize and describe your neuroimaging and behavioral data.
theme: jekyll-theme-cayman

baseurl: ""   # the subpath of your site, e.g. /blog
url: ""       # the base hostname & protocol for your site, e.g. http://example.com

show_downloads: false
show_footer: false
google_analytics: false

excerpt_separator: <!--more-->

collections:
  pages:
    output: true
    permalink: /:path

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      toc: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      toc: false

include:
  - _pages
  - _posts

exclude:
  - script
  - docs
  - old_website
  - README.md
  - LICENSE
  - Gemfile*
  - jekyll-theme-cayman.gemspec
